ARG REGISTRY=docker.io/library

FROM ${REGISTRY}/alpine:latest
WORKDIR /

RUN echo -e '#!/bin/sh\necho "Running dummy batch dmo-manager."' > /dmo-manager && \
  chmod +x /dmo-manager && \
  echo -e '#!/bin/sh\necho "Running dummy stream dmo-manager."' > /stream && \
  chmod +x /stream && \
  echo -e '#!/bin/sh\necho "Running dummy finalizer."' > /finalizer && \
  chmod +x /finalizer

ENTRYPOINT ["/dmo-manager"]
